include:
    - template: Code-Quality.gitlab-ci.yml

stages:
    - test
    - install
    - pack

code_quality_html:
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]

test:python3:
    stage: test
    image: cupy/cupy:v8.0.0
    script:
        - apt-get update -qq && apt-get upgrade -y
        - apt-get install -y python3 python3-pip
        - /usr/bin/python3 -m pip install --upgrade pip
        - pip3 install tifffile numpy nibabel h5py pillow numba matplotlib pytest pytest-cov
        # Online preview of tests that did run successfully
        - pytest tests --junitxml=report.xml    
    artifacts:
        when: always
        reports:
            junit: report.xml
    tags:
        - docker
        - gpu 
        
install:python3:
    stage: install
    image: cupy/cupy:v8.0.0
    script:
        - apt-get update -qq && apt-get upgrade -y
        - apt-get install -y python3 python3-pip
        - /usr/bin/python3 -m pip install --upgrade pip
        - pip3 install .
    tags:
    - docker
    - gpu 

pack:python3:
    stage: pack
    image: cupy/cupy:v8.0.0
    script:
        - apt-get update -qq && apt-get upgrade -y
        - apt-get install -y python3 python3-pip
        - /usr/bin/python3 -m pip install --upgrade pip
        - pip3 install pep517
        - python3 -m pep517.build --source --binary --out-dir dist/ .
    tags:
    - docker
    - gpu 
