stages:
    - test
    - install
    - pack

before_script:
    - apt-get update -qq && apt-get upgrade -y
    - apt-get install -y python3 python3-pip
    - apt-get install -y cuda-10-1

test:python3:
    stage: test
    image: nvidia/cuda:10.1-base
    script:
        - pip3 install -r requirements.txt
        - pytest
        - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    tags:
        - docker
        - gpu 
        
install:python3:
    stage: install
    image: nvidia/cuda:10.1-base
    script:
        - pip3 install .
    tags:
    - docker
    - gpu 

pack:python3:
    stage: pack
    image: nvidia/cuda:10.1-base
    script:
        - pip3 install pep517
        - pep517.build --source --binary --out-dir dist/ .
    tags:
    - docker
    - gpu 