stages:
    - test
    - install
    - pack

before_script:
    - apt-get update -qq && apt-get upgrade -y
    - apt-get install -y python3 python3-pip
    - /usr/bin/python3 -m pip install --upgrade pip

code_quality:
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]

test:python3:
    stage: test
    image: cupy/cupy:v8.0.0
    script:
        - pip3 install tifffile numpy nibabel h5py pillow numba matplotlib pytest pytest-cov
        - pytest --cov=SLIX --cov-config=.coveragerc tests
        - coverage run -m pytest 
        - coverage report
        - coverage xml
    artifacts:
        reports:
        cobertura: coverage.xml
    tags:
        - docker
        - gpu 
        
install:python3:
    stage: install
    image: cupy/cupy:v8.0.0
    script:
        - pip3 install .
    tags:
    - docker
    - gpu 

pack:python3:
    stage: pack
    image: cupy/cupy:v8.0.0
    script:
        - pip3 install pep517
        - python3 -m pep517.build --source --binary --out-dir dist/ .
    tags:
    - docker
    - gpu 
